/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ErikAnimatedProgressBar {
    'progress': number;
  }
  interface ErikRadioButton {
    'checked': boolean;
    'name': string;
    'scale': "small" | "medium" | "large";
    'value': string;
  }
  interface ErikRadioGroup {
    'name': string;
    'scale': "small" | "medium" | "large";
  }
  interface ErikToggleButton {
    'checked': boolean;
    'disabled': boolean;
    'tabIndex': number;
  }
}

declare global {


  interface HTMLErikAnimatedProgressBarElement extends Components.ErikAnimatedProgressBar, HTMLStencilElement {}
  var HTMLErikAnimatedProgressBarElement: {
    prototype: HTMLErikAnimatedProgressBarElement;
    new (): HTMLErikAnimatedProgressBarElement;
  };

  interface HTMLErikRadioButtonElement extends Components.ErikRadioButton, HTMLStencilElement {}
  var HTMLErikRadioButtonElement: {
    prototype: HTMLErikRadioButtonElement;
    new (): HTMLErikRadioButtonElement;
  };

  interface HTMLErikRadioGroupElement extends Components.ErikRadioGroup, HTMLStencilElement {}
  var HTMLErikRadioGroupElement: {
    prototype: HTMLErikRadioGroupElement;
    new (): HTMLErikRadioGroupElement;
  };

  interface HTMLErikToggleButtonElement extends Components.ErikToggleButton, HTMLStencilElement {}
  var HTMLErikToggleButtonElement: {
    prototype: HTMLErikToggleButtonElement;
    new (): HTMLErikToggleButtonElement;
  };
  interface HTMLElementTagNameMap {
    'erik-animated-progress-bar': HTMLErikAnimatedProgressBarElement;
    'erik-radio-button': HTMLErikRadioButtonElement;
    'erik-radio-group': HTMLErikRadioGroupElement;
    'erik-toggle-button': HTMLErikToggleButtonElement;
  }
}

declare namespace LocalJSX {
  interface ErikAnimatedProgressBar {
    'progress'?: number;
  }
  interface ErikRadioButton {
    'checked'?: boolean;
    'name'?: string;
    'onOnRadioButtonClick'?: (event: CustomEvent<any>) => void;
    'scale'?: "small" | "medium" | "large";
    'value'?: string;
  }
  interface ErikRadioGroup {
    'name'?: string;
    'scale'?: "small" | "medium" | "large";
  }
  interface ErikToggleButton {
    'checked'?: boolean;
    'disabled'?: boolean;
    'tabIndex'?: number;
  }

  interface IntrinsicElements {
    'erik-animated-progress-bar': ErikAnimatedProgressBar;
    'erik-radio-button': ErikRadioButton;
    'erik-radio-group': ErikRadioGroup;
    'erik-toggle-button': ErikToggleButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'erik-animated-progress-bar': LocalJSX.ErikAnimatedProgressBar & JSXBase.HTMLAttributes<HTMLErikAnimatedProgressBarElement>;
      'erik-radio-button': LocalJSX.ErikRadioButton & JSXBase.HTMLAttributes<HTMLErikRadioButtonElement>;
      'erik-radio-group': LocalJSX.ErikRadioGroup & JSXBase.HTMLAttributes<HTMLErikRadioGroupElement>;
      'erik-toggle-button': LocalJSX.ErikToggleButton & JSXBase.HTMLAttributes<HTMLErikToggleButtonElement>;
    }
  }
}


