/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ErikAnimatedProgressBar {
    'progress': number;
  }
}

declare global {


  interface HTMLErikAnimatedProgressBarElement extends Components.ErikAnimatedProgressBar, HTMLStencilElement {}
  var HTMLErikAnimatedProgressBarElement: {
    prototype: HTMLErikAnimatedProgressBarElement;
    new (): HTMLErikAnimatedProgressBarElement;
  };
  interface HTMLElementTagNameMap {
    'erik-animated-progress-bar': HTMLErikAnimatedProgressBarElement;
  }
}

declare namespace LocalJSX {
  interface ErikAnimatedProgressBar {
    'progress'?: number;
  }

  interface IntrinsicElements {
    'erik-animated-progress-bar': ErikAnimatedProgressBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'erik-animated-progress-bar': LocalJSX.ErikAnimatedProgressBar & JSXBase.HTMLAttributes<HTMLErikAnimatedProgressBarElement>;
    }
  }
}


