/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ErikAnimatedProgressBar {
    'progress': number;
  }
  interface ErikToggleButton {
    'checked': boolean;
    'disabled': boolean;
    'tabIndex': number;
  }
}

declare global {


  interface HTMLErikAnimatedProgressBarElement extends Components.ErikAnimatedProgressBar, HTMLStencilElement {}
  var HTMLErikAnimatedProgressBarElement: {
    prototype: HTMLErikAnimatedProgressBarElement;
    new (): HTMLErikAnimatedProgressBarElement;
  };

  interface HTMLErikToggleButtonElement extends Components.ErikToggleButton, HTMLStencilElement {}
  var HTMLErikToggleButtonElement: {
    prototype: HTMLErikToggleButtonElement;
    new (): HTMLErikToggleButtonElement;
  };
  interface HTMLElementTagNameMap {
    'erik-animated-progress-bar': HTMLErikAnimatedProgressBarElement;
    'erik-toggle-button': HTMLErikToggleButtonElement;
  }
}

declare namespace LocalJSX {
  interface ErikAnimatedProgressBar {
    'progress'?: number;
  }
  interface ErikToggleButton {
    'checked'?: boolean;
    'disabled'?: boolean;
    'tabIndex'?: number;
  }

  interface IntrinsicElements {
    'erik-animated-progress-bar': ErikAnimatedProgressBar;
    'erik-toggle-button': ErikToggleButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'erik-animated-progress-bar': LocalJSX.ErikAnimatedProgressBar & JSXBase.HTMLAttributes<HTMLErikAnimatedProgressBarElement>;
      'erik-toggle-button': LocalJSX.ErikToggleButton & JSXBase.HTMLAttributes<HTMLErikToggleButtonElement>;
    }
  }
}


